### ISSUE TITLE
Helm chart pulling 

### ISSUE THREAD

**Issue by GantzGit** [wavefrontHQ/helm#230]
Should the helmchart be pulling the latest version of projects.registry.vmware.com/tanzu_observability/proxy in the values file? I know the latest version is 11.3 on projects.registry.vmware.com

![image](https://user-images.githubusercontent.com/57367343/176788365-ea71721b-bc25-435b-b9f4-afe9a14c1c7b.png)

https://github.com/wavefrontHQ/helm/blob/228d1c3be7dd6dd645b492fa075e548b7acc95f3/wavefront/values.yaml#L244

**Comment by josephgee** [comment]
Hi @GantzGit , thanks for reaching out! We actually are waiting for a proxy fix to be able to upgrade this. A change was introduced that caused permission problems in some k8s environments. When we have this resolved, we'll be bumping this quickly. Thanks!
