### ISSUE TITLE
Refresh Wavefront helm dependency version in prometheus-storage-adapter

### ISSUE THREAD

**Issue by vavdoshka** [wavefrontHQ/helm#25]
Currently, the lock file specifies `1.2.1` as a dependency, while the newest version is `1.2.8` where we want to use some features.
Please update the lock file.

**Comment by vikramraman** [comment]
Thanks for raising the issue. We've released `v0.1.2` of the prometheus-storage-adapter helm chart which pulls in the latest `v1.2.8` of the wavefront chart.
