### ISSUE TITLE
wavefront proxy error

### ISSUE THREAD

**Issue by skanav1986** [wavefrontHQ/helm#3]
deploying wavefront using helm. The WF proxy container crashing with logs below:
Events:
  Type     Reason     Age                 From                                              Message
  ----     ------     ----                ----                                              -------
  Normal   Scheduled  115s                default-scheduler                                 Successfully assigned wavefront/wavefront-proxy-56d997f7cf-dqf5b to ip-10-0-1-79.us-east-2.compute.internal
  Normal   Pulled     6s (x11 over 114s)  kubelet, ip-10-0-1-79.us-east-2.compute.internal  Container image "wavefronthq/proxy:5.5" already present on machine
  **Warning  Failed     6s (x11 over 114s)  kubelet, ip-10-0-1-79.us-east-2.compute.internal  Error: container has runAsNonRoot and image will run as root**

**Comment by skanav1986** [comment]
[root@minikube ~]# kubectl get all -n wavefront
NAME                                                READY   STATUS                       RESTARTS   AGE
pod/wavefront-kube-state-metrics-7458f4cd44-vk52r   1/1     Running                      0          51m
pod/wavefront-proxy-56d997f7cf-dqf5b                0/1     CreateContainerConfigError   0          13m

**Comment by vikramraman** [comment]
@skanav1986 The proxy container runs as root. We don't enforce `runAsNonRoot` within our helm charts. Is this something you added when deploying or is enforced in your cluster?

Does the proxy deployment have any security context such as:
```
securityContext:
          runAsNonRoot: true
```

**Comment by skanav1986** [comment]
No i didnt..It was already there.

**Comment by skanav1986** [comment]
issue solved....was because of some org policies forced into pods
