### ISSUE TITLE
Deploying Helm to TKG - need privileged role binding

### ISSUE THREAD

**Issue by howardyoo** [wavefrontHQ/helm#5]
When deploying WF Helm on TKG (Tanzu Kubernetes Grid), the following error is observed: 
> Error: container has runAsNonRoot and image will run as root

So, the Helm deployment does not work. By manually binding privileged role to the default service account of Wavefront is required:
> kubectl create clusterrolebinding x:wavefront:wavefront-collector:cluster-admin --clusterrole=cluster.admin --serviceaccount=wavefront:wavefront-collector

Then export and reapplied the yaml for 
> daemonset.apps/wavefront-collector

It seems that RBAC setup the helm v3 deploy performs for TKG is insufficient. Not sure whether cluster.admin role is the right role for the binding, but this needs to be fixed.

** originally reported by Kendall Admins from Pivotal.

**Comment by kadkins-pivotal** [comment]
Please note that this is TKG cluster deployed on AWS via TMC. I executed the following role binding to resolve the PSP constraint:

>  kubectl create clusterrolebinding x:wavefront:default:psp:privileged --clusterrole=vmware-system-tmc-psp-privileged --serviceaccount=wavefront:default

The volumes could not be mounted by daemonset.apps/wavefront-collector until I applied the clusterrolebinding Howard calls out above.

**Comment by vikramraman** [comment]
@kadkins-pivotal @howardyoo Would something similar to this https://github.com/wavefrontHQ/helm/pull/13 work?

**Comment by vikramraman** [comment]
Closing this. Proxy container does not run as root starting with proxy v8.2. For TMC, there'll be a UI enablement option soon for Wavefront collector / proxy that should take care of this.
